version: "3"
services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tornado
      MYSQL_DATABASE: tornado
  adminer:
    image: adminer
    restart: always
    ports:
      - 3307:8080